Controllers/LinkController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using NederlandsWebsiteVDS.BL;
using NederlandsWebsiteVDS.Models;

namespace NederlandsWebsiteVDS.Controllers
{
    public class LinkController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RoleCheck(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naam,Url")] Link link)
        {
            if (ModelState.IsValid)
            {
                db.Link.Add(link);
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }

            return View(link);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Link.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naam,Url")] Link link)
        {
            if (ModelState.IsValid)
            {
                db.Entry(link).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }
            return View(link);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Link.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Link link = db.Link.Find(id);
            db.Link.Remove(link);
            db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UitlegController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using NederlandsWebsiteVDS.BL;
using NederlandsWebsiteVDS.Models;

namespace NederlandsWebsiteVDS.Controllers
{
    public class UitlegController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RoleCheck(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam");
            return View();
        }

        [ValidateInput(false)]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([Bind(Include = "Id,Naam,Context,OnderwerpId")] Uitleg uitleg)
        {
            if (ModelState.IsValid)
            {
                db.Uitleg.Add(uitleg);
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }

            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", uitleg.OnderwerpId);
            return View(uitleg);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uitleg uitleg = db.Uitleg.Find(id);
            if (uitleg == null)
            {
                return HttpNotFound();
            }
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", uitleg.OnderwerpId);
            return View(uitleg);
        }

        [ValidateInput(false)]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([Bind(Include = "Id,Naam,Context,OnderwerpId")] Uitleg uitleg)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uitleg).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", uitleg.OnderwerpId);
            return View(uitleg);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uitleg uitleg = db.Uitleg.Find(id);
            if (uitleg == null)
            {
                return HttpNotFound();
            }
            return View(uitleg);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uitleg uitleg = db.Uitleg.Find(id);
            db.Uitleg.Remove(uitleg);
            db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }

        public ActionResult View(int? uitleg)
        {
            if (uitleg == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var selectedUitleg = db.Uitleg.Find(uitleg);

            if (selectedUitleg == null)
            {
                return HttpNotFound();
            }

            return View(selectedUitleg);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Admin/Index.cshtml
@model NederlandsWebsiteVDS.Models.Admin
@{
    ViewBag.Title = "Index";
}   
<style>
    .table-fixed {
         table-layout: fixed;
    }
    .table-fixed td {
         word-wrap: break-word;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <hr />
            <h1>Admin panel</h1>
            <h2>Alle Gebruikers</h2>
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Email</th>
                    <th>Voornaam</th>
                    <th>Achternaam</th>
                    <th>Aanmaak datum</th>
                    <th>Laatst aangepast</th>
                </tr>

                @foreach (var item in Model.GebruikerVM)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                        <td>@Html.DisplayFor(modelItem => item.Voornaam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Achternaam)</td>
                        <td>@Html.DisplayFor(modelItem => item.DataAdded)</td>
                        <td>@Html.DisplayFor(modelItem => item.DateEdit)</td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <h2>Alle Categorien</h2>
                <p>@Html.ActionLink("Nieuwe categorie aanmaken", "Create", "Categorie")</p>
                <table class="table">
                    <tr>
                        <th class="col-md-4">Categorie</th>
                        <th class="col-md-2"></th>
                    </tr>
                    @foreach (var item in Model.CategorieVM)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Naam)</td>
                            <td>@Html.ActionLink("Aanpassen", "Edit", "Categorie", new { id = item.Id }, null) | @Html.ActionLink("Verwijderen", "Delete", "Categorie", new { id = item.Id }, null)</td>
                        </tr>
                    }
                </table>
            </div>

            <div class="col-md-6">
                <h2>Alle Onderwerpen</h2>
                <p>@Html.ActionLink("Nieuwe onderwerp aanmaken", "Create", "Onderwerp")</p>
                <table class="table">
                    <tr>
                        <th class="col-md-4">Onderwerp</th>
                        <th class="col-md-2"></th>
                    </tr>
                    @foreach (var item in Model.OnderwerpVM)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Naam)</td>
                            <td>@Html.ActionLink("Aanpassen", "Edit", "Onderwerp", new { id = item.Id }, null) | @Html.ActionLink("Verwijderen", "Delete", "Onderwerp", new { id = item.Id }, null)</td>

                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="col-md-12">
            <h2>Alle Links</h2>
            <p>@Html.ActionLink("Nieuwe link aanmaken", "Create", "Link")</p>
            <table class="table">
                <tr>
                    <th class="col-md-5">Link Naam</th>
                    <th class="col-md-5">Url</th>
                    <th class="col-md-2"></th>
                </tr>
                @foreach (var item in Model.LinkVM)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Naam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Url)</td>
                        <td>@Html.ActionLink("Aanpassen", "Edit", "Link", new { id = item.Id }, null) | @Html.ActionLink("Verwijderen", "Delete", "Link", new { id = item.Id }, null)</td>
                    </tr>
                }
            </table>

            <h2>Alle Opdrachten</h2>
            <p>@Html.ActionLink("Nieuwe opdracht aanmaken", "Create", "Opdracht")</p>
            <table class="table table-fixed">
                <tr>
                    <th class="col-md-2">Onderwerp</th>
                    <th class="col-md-2">Naam</th>
                    <th class="col-md-6">Context</th>
                    <th class="col-md-2"></th>
                </tr>
                @foreach (var item in Model.OpdrachtVM)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Onderwerp.Naam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Naam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Context)</td>
                        <td>@Html.ActionLink("Aanpassen", "Edit", "Opdracht", new { id = item.Id }, null) | @Html.ActionLink("Verwijderen", "Delete", "Opdracht", new { id = item.Id }, null)</td>
                    </tr>
                }
            </table>

            <h2>Alle Uitleg</h2>
            <p>@Html.ActionLink("Nieuwe uitleg aanmaken", "Create", "Uitleg")</p>
            <table class="table table-fixed">
                <tr>
                    <th class="col-md-2">Onderwerp</th>
                    <th class="col-md-2">Naam</th>
                    <th class="col-md-6">Context</th>
                    <th class="col-md-2"></th>
                </tr>
                @foreach (var item in Model.UitlegVM)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Onderwerp.Naam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Naam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Context)</td>
                        <td>@Html.ActionLink("Aanpassen", "Edit", "Uitleg", new {id = item.Id}, null) | @Html.ActionLink("Verwijderen", "Delete", "Uitleg", new {id = item.Id}, null)</td>
                    </tr>
                }
            </table>
            <h2>Alle Vragen</h2>
            <p>@Html.ActionLink("Nieuwe uitleg aanmaken", "Create", "Uitleg")</p>
            <table class="table table-fixed">
                <tr>
                    <th class="col-md-2">Onderwerp</th>
                    <th class="col-md-2">Vraag</th>
                    <th class="col-md-2"></th>
                </tr>
                @foreach (var item in Model.VraagVM)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Opdracht.Naam)</td>
                        <td>@Html.DisplayFor(modelItem => item.Naam)</td>
                        <td>@Html.ActionLink("Aanpassen", "Edit", "Uitleg", new { id = item.Id }, null) | @Html.ActionLink("Verwijderen", "Delete", "Uitleg", new { id = item.Id }, null)</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>