Models/Onderwerp.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NederlandsWebsiteVDS.Models
{
    public class Onderwerp
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string Naam { get; set; }

        [Required]
        [ForeignKey("Categorie")]
        public int CategorieId { get; set; }

        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Uitleg> UitlegCollection { get; set; }
        public virtual ICollection<Opdracht> OpdrachtCollection { get; set; }
    }
}

Controllers/OnderwerpController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using NederlandsWebsiteVDS.BL;
using NederlandsWebsiteVDS.Models;

namespace NederlandsWebsiteVDS.Controllers
{
    public class OnderwerpController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RoleCheck(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CategorieId = new SelectList(db.Categorie, "Id", "Naam");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naam,CategorieId")] Onderwerp onderwerp)
        {
            if (ModelState.IsValid)
            {
                db.Onderwerp.Add(onderwerp);
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }

            ViewBag.CategorieId = new SelectList(db.Categorie, "Id", "Naam", onderwerp.CategorieId);
            return View(onderwerp);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Onderwerp onderwerp = db.Onderwerp.Find(id);
            if (onderwerp == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategorieId = new SelectList(db.Categorie, "Id", "Naam", onderwerp.CategorieId);
            return View(onderwerp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naam,CategorieId")] Onderwerp onderwerp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(onderwerp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.CategorieId = new SelectList(db.Categorie, "Id", "Naam", onderwerp.CategorieId);
            return View(onderwerp);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Onderwerp onderwerp = db.Onderwerp.Find(id);
            if (onderwerp == null)
            {
                return HttpNotFound();
            }
            return View(onderwerp);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Onderwerp onderwerp = db.Onderwerp.Find(id);
            db.Onderwerp.Remove(onderwerp);
            db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }

        public new ActionResult View(string categorie, string onderwerp)
        {
            if (categorie == "" || onderwerp == "")
                return HttpNotFound();
            var opdrachten = from m in db.Opdracht select m;
            var uitleg = from m in db.Uitleg select m;
            opdrachten = opdrachten.Where(s => s.Onderwerp.Naam.Contains(onderwerp));
            uitleg = uitleg.Where(u => u.Onderwerp.Naam.Contains(onderwerp));

            var onderwerpVm = new Admin
            {
                UitlegVM = new List<Uitleg>(uitleg),
                OpdrachtVM = new List<Opdracht>(opdrachten)
            };
            return View(onderwerpVm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OpdrachtController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using NederlandsWebsiteVDS.BL;
using NederlandsWebsiteVDS.Models;

namespace NederlandsWebsiteVDS.Controllers
{
    public class OpdrachtController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RoleCheck(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam");
            return View();
        }

        [ValidateInput(false)]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([Bind(Include = "Id,Naam,Context,OnderwerpId")] Opdracht opdracht)
        {
            if (ModelState.IsValid)
            {
                db.Opdracht.Add(opdracht);
                db.SaveChanges();
                return RedirectToAction("Create", "Vraag", new { id = opdracht.Id});
            }

            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", opdracht.OnderwerpId);
            return View(opdracht);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opdracht opdracht = db.Opdracht.Find(id);
            if (opdracht == null)
            {
                return HttpNotFound();
            }

            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", opdracht.OnderwerpId);
            return View(opdracht);
        }

        [ValidateInput(false)]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([Bind(Include = "Id,Naam,Context,OnderwerpId")] Opdracht opdracht)
        {
            if (ModelState.IsValid)
            {
                db.Entry(opdracht).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", opdracht.OnderwerpId);
            return View(opdracht);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opdracht opdracht = db.Opdracht.Find(id);
            if (opdracht == null)
            {
                return HttpNotFound();
            }
            return View(opdracht);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Opdracht opdracht = db.Opdracht.Find(id);
            db.Opdracht.Remove(opdracht);
            db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }

        public ActionResult View(int? opdracht)
        {
            if (opdracht == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var selectedOpdracht = db.Opdracht.Find(opdracht);

            if (selectedOpdracht == null)
            {
                return HttpNotFound();
            }

            return View(selectedOpdracht);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UitlegController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using NederlandsWebsiteVDS.BL;
using NederlandsWebsiteVDS.Models;

namespace NederlandsWebsiteVDS.Controllers
{
    public class UitlegController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [RoleCheck(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam");
            return View();
        }

        [ValidateInput(false)]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([Bind(Include = "Id,Naam,Context,OnderwerpId")] Uitleg uitleg)
        {
            if (ModelState.IsValid)
            {
                db.Uitleg.Add(uitleg);
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }

            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", uitleg.OnderwerpId);
            return View(uitleg);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uitleg uitleg = db.Uitleg.Find(id);
            if (uitleg == null)
            {
                return HttpNotFound();
            }
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", uitleg.OnderwerpId);
            return View(uitleg);
        }

        [ValidateInput(false)]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([Bind(Include = "Id,Naam,Context,OnderwerpId")] Uitleg uitleg)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uitleg).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.OnderwerpId = new SelectList(db.Onderwerp, "Id", "Naam", uitleg.OnderwerpId);
            return View(uitleg);
        }

        [RoleCheck(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uitleg uitleg = db.Uitleg.Find(id);
            if (uitleg == null)
            {
                return HttpNotFound();
            }
            return View(uitleg);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uitleg uitleg = db.Uitleg.Find(id);
            db.Uitleg.Remove(uitleg);
            db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }

        public ActionResult View(int? uitleg)
        {
            if (uitleg == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var selectedUitleg = db.Uitleg.Find(uitleg);

            if (selectedUitleg == null)
            {
                return HttpNotFound();
            }

            return View(selectedUitleg);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Onderwerp/Create.cshtml
@model NederlandsWebsiteVDS.Models.Onderwerp

@{
    ViewBag.Title = "Create";
}

<script>
    tinymce.init({
        selector: 'textarea#editcontext',
        plugin: 'a_tinymce_plugin',
        a_plugin_option: true,
        a_configuration_option: 400
    });
</script>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <hr />
            <h2>Create</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Onderwerp</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategorieId, "CategorieId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("CategorieId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategorieId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Terug naar het admin panel", "Index", "Admin")
            </div>
            <hr />
        </div>
</div>

Views/Onderwerp/Delete.cshtml
@model NederlandsWebsiteVDS.Models.Onderwerp

@{
    ViewBag.Title = "Delete";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Delete</h2>
            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>Onderwerp</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Categorie.Naam)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Categorie.Naam)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Naam)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Naam)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Terug naar het admin panel", "Index", "Admin")
                    </div>
                    <hr />
                }
            </div>
        </div>
    </div>
</div>

Views/Onderwerp/Edit.cshtml
@model NederlandsWebsiteVDS.Models.Onderwerp

@{
    ViewBag.Title = "Edit";
}
<div class="container">
    <div class="row">
        <h2>Edit</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Onderwerp</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CategorieId, "CategorieId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CategorieId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategorieId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Terug naar het admin panel", "Index", "Admin")
        </div>
        <hr />
    </div>
</div>

Views/Onderwerp/View.cshtml
@model NederlandsWebsiteVDS.Models.Admin

@{
    ViewBag.Title = "View";
}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-left">
            <hr />
            @if (Model.OpdrachtVM.Count != 0)
            {
                <h3>Opdrachten</h3>
                <ul class="list-unstyled">
                    @foreach (var item in Model.OpdrachtVM)
                    {
                        <li>
                            <a href="@Url.Action("View", "Opdracht", new {opdracht = item.Id})">@Html.DisplayFor(modelItem => item.Naam)</a>
                        </li>
                    }
                </ul>
            }
            else
            {
                <h3>Er zijn geen opdrachten bij dit onderwerp.</h3>
            }
            @if (Model.UitlegVM.Count != 0)
            {
                <h3>Uitleg</h3>
                <ul class="list-unstyled">
                    @foreach (var item in Model.UitlegVM)
                    {
                        <li>
                            <a class="h5" href="@Url.Action("View", "Uitleg", new {uitleg = item.Id})">@Html.DisplayFor(modelItem => item.Naam)</a>
                        </li>
                    }
                </ul>
            }
            else
            {
                <h3>Er is geen uitleg bij dit onderwerp.</h3>
            }
        </div>
    </div>
</div>